// Mock data for VONKAM CRM
export const mockGeo = {
  counties: [
    {
      name: "Broward",
      zips: [
        { zip: "33021", name: "Hollywood", cases_count: 26, hot_count: 8 },
        { zip: "33023", name: "Miramar", cases_count: 19, hot_count: 6 },
      ],
    },
    {
      name: "Miami-Dade",
      zips: [
        { zip: "33147", name: "NW Miami", cases_count: 31, hot_count: 10 },
        { zip: "33142", name: "Allapattah", cases_count: 22, hot_count: 7 },
      ],
    },
  ],
};

export type LeadStatus = "Active" | "Hot" | "Signed" | "Loan Mod" | "Closed";

export const mockCases = [
  {
    id: "c1",
    case_number: "CACE-25-012345",
    filing_date: "2025-10-24",
    status: "Active" as LeadStatus,
    doc_type: "Lis Pendens",
    owner_1: "Ben Adams",
    situs_address: "123 Main St, Hollywood, FL 33021",
    mailing_address: "456 Oak Ave, Miami, FL 33142",
    lead_score: 8,
    phones_verified: 2,
    phones_total: 3,
    emails_verified: 1,
    emails_total: 2,
    amount_owed: 245000,
    plaintiff: "Wells Fargo Bank, N.A.",
    latest_event_desc: "Pre-foreclosure notice published",
    latest_event_at: "2025-10-31T21:05:00Z",
    next_action: "Schedule call",
    last_touch: "2025-11-01T14:30:00Z",
  },
  {
    id: "c2",
    case_number: "CACE-25-012346",
    filing_date: "2025-10-20",
    status: "Hot" as LeadStatus,
    doc_type: "Lis Pendens",
    owner_1: "Sarah Miller",
    situs_address: "456 Palm Ave, Miramar, FL 33023",
    mailing_address: "456 Palm Ave, Miramar, FL 33023",
    lead_score: 9,
    phones_verified: 3,
    phones_total: 3,
    emails_verified: 2,
    emails_total: 2,
    amount_owed: 189000,
    plaintiff: "Bank of America, N.A.",
    latest_event_desc: "Final judgment entered",
    latest_event_at: "2025-10-28T15:30:00Z",
    next_action: "Send offer",
    last_touch: "2025-10-30T10:00:00Z",
  },
  {
    id: "c3",
    case_number: "CACE-25-012347",
    filing_date: "2025-10-15",
    status: "Active" as LeadStatus,
    doc_type: "Notice of Sale",
    owner_1: "James Wilson",
    situs_address: "789 Ocean Blvd, NW Miami, FL 33147",
    mailing_address: "100 Different St, Miami, FL 33147",
    lead_score: 7,
    phones_verified: 1,
    phones_total: 2,
    emails_verified: 0,
    emails_total: 1,
    amount_owed: 320000,
    plaintiff: "JPMorgan Chase Bank, N.A.",
    latest_event_desc: "Sale scheduled for December 15",
    latest_event_at: "2025-10-25T12:00:00Z",
    next_action: "Initial outreach",
    last_touch: null,
  },
  {
    id: "c4",
    case_number: "CACE-25-012348",
    filing_date: "2025-09-10",
    status: "Signed" as LeadStatus,
    doc_type: "Lis Pendens",
    owner_1: "Maria Garcia",
    situs_address: "321 River Rd, Allapattah, FL 33142",
    mailing_address: "321 River Rd, Allapattah, FL 33142",
    lead_score: 9,
    phones_verified: 2,
    phones_total: 2,
    emails_verified: 1,
    emails_total: 1,
    amount_owed: 175000,
    plaintiff: "Nationstar Mortgage LLC",
    latest_event_desc: "Contract signed - pending closing",
    latest_event_at: "2025-10-20T09:00:00Z",
    next_action: "Coordinate closing",
    last_touch: "2025-10-29T16:00:00Z",
  },
  {
    id: "c5",
    case_number: "CACE-25-012349",
    filing_date: "2025-08-05",
    status: "Loan Mod" as LeadStatus,
    doc_type: "Modification",
    owner_1: "Robert Chen",
    situs_address: "555 Lake View Dr, Hollywood, FL 33021",
    mailing_address: "555 Lake View Dr, Hollywood, FL 33021",
    lead_score: 6,
    phones_verified: 2,
    phones_total: 3,
    emails_verified: 1,
    emails_total: 2,
    amount_owed: 210000,
    plaintiff: "Ocwen Loan Servicing",
    latest_event_desc: "Loan modification in progress",
    latest_event_at: "2025-10-18T11:00:00Z",
    next_action: "Follow up on mod status",
    last_touch: "2025-10-25T14:00:00Z",
  },
];

export const mockCaseDetail = {
  id: "c1",
  case_number: "CACE-25-012345",
  filing_date: "2025-10-24",
  status: "Active" as LeadStatus,
  doc_type: "Lis Pendens",
  lead_score: 8,
  amount_owed: 245000,
  plaintiff: "Wells Fargo Bank, N.A.",
  property: {
    address: "123 Main St, Hollywood, FL 33021",
    mailing_address: "456 Oak Ave, Miami, FL 33142",
    apn: "50-42-05-12-0010",
    portal_link: "https://bcclerk.broward.org/...",
    estimated_value: 385000,
    equity: 140000,
  },
  parties: [
    { name: "Ben Adams", role: "Defendant", primary: true },
    { name: "Lisa Adams", role: "Defendant", primary: false },
    { name: "Wells Fargo Bank, N.A.", role: "Plaintiff", primary: true },
    { name: "Smith & Associates P.A.", role: "Attorney", primary: false },
  ],
  contacts: [
    {
      name: "Ben Adams",
      role: "Owner",
      phones: [
        { number: "(305) 555-1234", verified: "verified", type: "Mobile" },
        { number: "(305) 555-5678", verified: "verified", type: "Home" },
        { number: "(305) 555-9012", verified: "unknown", type: "Work" },
      ],
      emails: [
        { email: "ben.adams@email.com", status: "verified" as const },
        { email: "badams@work.com", status: "unknown" as const },
      ],
    },
    {
      name: "Lisa Adams",
      role: "Co-Owner",
      phones: [{ number: "(305) 555-3456", verified: "verified", type: "Mobile" }],
      emails: [{ email: "lisa.adams@email.com", status: "verified" as const }],
    },
  ],
  events: [
    {
      type: "Docket Update",
      desc: "Pre-foreclosure notice published",
      at: "2025-10-31T21:05:00Z",
      automated: true,
    },
    {
      type: "AI Alert",
      desc: "High intent detected - owner searched 'sell my house fast' online",
      at: "2025-10-30T14:00:00Z",
      automated: true,
    },
    {
      type: "VA Note",
      desc: "Called Ben - no answer, left voicemail about options",
      at: "2025-10-29T10:30:00Z",
      automated: false,
    },
    {
      type: "SMS Sent",
      desc: "Sent initial outreach text message",
      at: "2025-10-28T15:45:00Z",
      automated: false,
    },
    {
      type: "Docket Update",
      desc: "Lis Pendens filed",
      at: "2025-10-24T09:00:00Z",
      automated: true,
    },
    {
      type: "System",
      desc: "Lead created from county records import",
      at: "2025-10-24T08:00:00Z",
      automated: true,
    },
  ],
};
